# Generated by Django 4.0.3 on 2022-03-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdcapAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name': 'Movimiento ', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdcapAPP.cliente', unique=True),
        ),
        migrations.AlterField(
            model_name='movimientodetalle',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='AdcapAPP.movimiento', unique=True),
        ),
        migrations.AlterField(
            model_name='movimientodetalle',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='T', max_length=30, verbose_name='Tipo de Movimiento'),
        ),
    ]
