# Generated by Django 4.0.3 on 2022-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdcapAPP', '0003_alter_movimientodetalle_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodetalle',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='Ingreso', max_length=30, verbose_name='Tipo de Movimiento'),
        ),
    ]
