# Generated by Django 4.0.3 on 2022-03-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdcapAPP', '0004_alter_movimientodetalle_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodetalle',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='AdcapAPP.movimiento', unique=True),
        ),
    ]
