# Generated by Django 4.0.3 on 2022-03-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdcapAPP', '0005_alter_movimientodetalle_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_cliente', to='AdcapAPP.cliente', unique=True),
        ),
    ]
