# Generated by Django 4.0.3 on 2022-03-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdcapAPP', '0006_alter_cuenta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodetalle',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='AdcapAPP.movimiento'),
        ),
    ]
