# Generated by Django 4.0.3 on 2022-03-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdcapAPP', '0007_alter_movimientodetalle_movimiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimiento',
            unique_together={('cliente', 'fecha')},
        ),
    ]
