# Generated by Django 4.0.3 on 2022-03-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdcapAPP', '0008_alter_movimiento_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimiento',
            unique_together=set(),
        ),
    ]
